WIREGUARD_IMAGE: "ghcr.io/jodevsa/wireguard-operator/wireguard:sha-d2fac4d22a3ae9ca2479614c3f93fa9f4ed71598"
OPERATOR_IMAGE: "ghcr.io/jodevsa/wireguard-operator/operator:sha-d2fac4d22a3ae9ca2479614c3f93fa9f4ed71598"