WIREGUARD_IMAGE: "ghcr.io/jodevsa/wireguard-operator/wireguard:sha-64c91a661f4ae6dce41e311386cfe5b8309e816c"
OPERATOR_IMAGE: "ghcr.io/jodevsa/wireguard-operator/operator:sha-64c91a661f4ae6dce41e311386cfe5b8309e816c"