WIREGUARD_IMAGE: ""
OPERATOR_IMAGE: "ghcr.io/jodevsa/wireguard-operator/operator:sha-5e833cb99230793a571cdcf519dea0abac457e6c"
BUNDLE_IMAGE: "ghcr.io/jodevsa/wireguard-operator/bundle:sha-5e833cb99230793a571cdcf519dea0abac457e6c"